[package]
name = "rustlight"
version = "0.2.0"
authors = ["Adrien Gruson <adrien.gruson@gmail.com>"]
edition = "2018"

[[bin]]
name = "rustlight"
doc = false

[features]
# No default features are enable by default
default = ["image", "embree-rs", "pbrt"]
pbrt = ["pbrt_rs"]
embree = ["embree-rs"]

[dependencies]
image = { version =  "*", optional = true }
rayon = "*"
rand = "*"
tobj = "*"
embree-rs = { version = "*" , optional = true }
serde = "1.0"
serde_derive = "1.0" 
serde_json = "1.0"
byteorder = "*"
clap = "*"
pbr = "*"
log = "*"
env_logger = "*"
# To know number of threads
num_cpus = "*"
# - openexr image format (output)
exr = { version = "0.7.2", optional = true }
# - pbrt image format (input)
pbrt_rs = { git = "https://github.com/beltegeuse/pbrt_rs", optional = true }

[dependencies.cgmath]
version = "*"
features = ["serde"]
